language: shell
services:
- docker
os: linux
dist: focal
cache: npm
install:
- echo $DISCORD_TOKEN > .env
- docker build -t socket-bot .
deploy:
  provider: gae
  keyfile: client-secret.json
  project: light-lambda-245521
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_75ef5263a21f_key -iv $encrypted_75ef5263a21f_iv
  -in client-secret.json.enc -out client-secret.json -d
